
MIN <- 2.225074e-308
FDR <- 0.05

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 5) {
    cat("\nUsage: <cpm> <file_list> <control> <case> <outdir>\n")
    cat("\n<cpm>         cpm for each GBC\n")
    cat("<file_list>   tsv containing the sample ID (col1) and the path of the \"groups.tsv\" (col2) generated by barcode-groups\n")
    cat("<control>     label defining the control (as in <file_list> col3)\n")
    cat("<case>        label defining the case (as in <file_list> col3)\n")
    cat("<outdir>      where the list of TIC and the volcano plot are saved\n\n")
    q()
}

CPM <- args[1]
FILE_LIST <- args[2]
CTRL <- args[3]
CASE <- args[4]
OUT <- args[5]

cpm <- read.table(CPM, sep = "\t", header = TRUE)

file_list <- read.table(FILE_LIST, header = FALSE, sep = "\t")

idx_col_p0 <- match(file_list[file_list[,3] == CTRL,1], colnames(cpm))
idx_col_t <- match(file_list[file_list[,3] == CASE,1], colnames(cpm))

n_p0 <- length(idx_col_p0)
if (n_p0 == 1) {
    tot_p0 <- sum(cpm[,idx_col_p0])
    cpm_p0_max <- round(cpm[,idx_col_p0])
    which_cpm_p0_max <- rep(idx_col_p0, nrow(cpm))
} else {
    tot_p0 <- colSums(cpm[,idx_col_p0])
    cpm_p0_max <- apply(cpm[,idx_col_p0], 1, function(x) round(max(x)))
    which_cpm_p0_max <- apply(cpm[,idx_col_p0], 1, function(x) which(x == max(x)))
}

cpm_t <- round(cpm[,idx_col_t])
tot_t <- colSums(cpm_t)

fisher.test.pval <- matrix(1, nrow = nrow(cpm), ncol = ncol(cpm_t))
fisher.test.odds <- matrix(1, nrow = nrow(cpm), ncol = ncol(cpm_t))
for (i in 1:nrow(cpm)) {
    for (j in 1:ncol(fisher.test.pval)) {
        fisher_table <- matrix(c(cpm_t[i,j],cpm_p0_max[i],tot_t[j]-cpm_t[i,j],tot_p0[which_cpm_p0_max[i]]-cpm_p0_max[i]), nrow=2, ncol=2)
        f <- fisher.test(fisher_table, alternative = "greater")
        fisher.test.pval[i,j] <- f$p.value
        fisher.test.odds[i,j] <- f$estimate
    }
}

F_bonferroni <- matrix(1, nrow = nrow(cpm), ncol = ncol(cpm_t))
for (j in 1:ncol(fisher.test.pval)) {
    F_bonferroni[,j] <- p.adjust(fisher.test.pval[,j], method = "bonferroni")
}     

# num_t_sign <- rowSums(F_bonferroni_twice < 0.05)
# avg_pval <- apply(F_bonferroni_twice, 1, mean)
# best_pval <- apply(F_bonferroni_twice, 1, min)

num_t_sign <- rowSums(F_bonferroni < FDR)

avg_pval <- apply(F_bonferroni, 1, mean)
best_pval <- apply(F_bonferroni, 1, min)
best_pval[best_pval == 0] <- rep(MIN, sum(best_pval == 0))
median_pval <- apply(F_bonferroni, 1, median)
median_pval[median_pval == 0] <- rep(MIN, sum(median_pval == 0))

PLOT_FISHER <- file.path(OUT, "dotplot.pdf")
ncols <- ceiling(length((idx_col_t-1)/2))
pdf(PLOT_FISHER, width = 2.5*ncols, height = 5)
par(mfrow=c(2,ncols))
x <- log10(rowSums(cpm_t))[num_t_sign > 1]
y <- -log10(best_pval)[num_t_sign > 1]
ymax <- max(-log10(best_pval)[num_t_sign > 1])
for (i in 2:length(idx_col_t)) {
    plot(log10(rowSums(cpm_t))[num_t_sign == i], -log10(best_pval)[num_t_sign == i], 
    main = i, xlab = "-log10(best_pval)", ylab = "log10(cpm)", xlim = c(min(x),max(x)), ylim = c(min(y),max(y)))
}
dev.off()

df_fisher <- data.frame(F_bonferroni)
df_odds <- data.frame(fisher.test.odds)
rownames(df_fisher) <- rownames(df_odds) <- rownames(cpm)
colnames(df_fisher) <- colnames(df_odds) <- colnames(cpm)[idx_col_t]

OCC <- ceiling(length(idx_col_t)/2+1)
idx_TIC <- which(num_t_sign >= OCC)
TIC <- rownames(df_fisher)[idx_TIC]

is.TIC <- rep(FALSE, nrow(df_fisher))
is.TIC[idx_TIC] <- rep(TRUE, length(idx_TIC))
df_fisher <- cbind(df_fisher, is.selected = as.numeric(is.TIC))
df_odds <- cbind(df_odds, is.selected = as.numeric(is.TIC))

OUT_TIC <- file.path(OUT, "fisher.tsv")
write.table(df_fisher, file = OUT_TIC, sep = "\t", quote = FALSE)

OUT_TIC <- file.path(OUT, "fisher_odds.tsv")
write.table(df_odds, file = OUT_TIC, sep = "\t", quote = FALSE)

OUT_TIC <- file.path(OUT, "list.txt")
write.table(TIC, file = OUT_TIC, row.names = FALSE, col.names = FALSE, quote = FALSE)

q()


