
MIN_DETECT <- 2
EPSILON <- 1

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 5) {
    cat("\nUsage: <cpm> <file_list> <control> <case> <out>\n")
    cat("\n<cpm>      count per million for each GBC\n")
    cat("<file_list>   tsv containing the sample ID (col1) and the path of the \"groups.tsv\" (col2) generated by barcode-groups\n")
    cat("<control>     label defining the control (as in <file_list> col3)\n")
    cat("<case>        label defining the case (as in <file_list> col3)\n")
    cat("<outdir>      where the list of TIC and the volcano plot are saved\n\n")
    q()
}

CPM <- args[1]
FILE_LIST <- args[2]
CTRL <- args[3]
CASE <- args[4]
OUT <- args[5]

cpm <- read.table(CPM, sep = "\t", header = TRUE)

idx <- which(rowSums(cpm > 0) >= MIN_DETECT)
cpm <- cpm[idx,]

file_list <- read.table(FILE_LIST, header = FALSE, sep = "\t")

idx_col_p0 <- match(file_list[file_list[,3] == CTRL,1], colnames(cpm))
idx_col_t <- match(file_list[file_list[,3] == CASE,1], colnames(cpm))

if (length(idx_col_p0) == 1) {
    avg_p0 <- cpm[,idx_col_p0]
} else {
    avg_p0 <- apply(cpm[,idx_col_p0], 1, mean)
}
if (length(idx_col_t) == 1) {
    avg_t <- cpm[,idx_col_t]
} else {
    avg_t <- apply(cpm[,idx_col_t], 1, mean)
}
logfc <- log2((avg_t+EPSILON) / (avg_p0+EPSILON))
a <- log2((avg_t+EPSILON)*(avg_p0+EPSILON))/2

wtest.res.pval <- unlist(lapply(1:nrow(cpm), function(i) {
     if (is.na(logfc[i])) {
         1
     } else {
         if (logfc[i] > 0) {
             alt = "less"
         } else {
             alt = "greater"
         }
         wilcox.test(x = drop(t(cpm[i,idx_col_p0])), y = drop(t(cpm[i,idx_col_t])), alternative = alt)$p.value 
         }
     }
)
)

df_wilcox <- data.frame(avg.cpm.ctrl = avg_p0, avg.cpm.case = avg_t, log.avg = a, log2fc = logfc, pval = wtest.res.pval)
rownames(df_wilcox) <- rownames(cpm)

idx_TIC <- which(df_wilcox$log2fc > 0 & df_wilcox$pval < 0.1)
TIC <- rownames(df_wilcox)[idx_TIC]

is.TIC <- rep(FALSE, nrow(df_wilcox))
is.TIC[idx_TIC] <- rep(TRUE, length(idx_TIC))
df_wilcox <- cbind(df_wilcox, is.selected = as.numeric(is.TIC))

OUT_TIC <- file.path(OUT, "wilcox.tsv")
write.table(df_wilcox, file = OUT_TIC, sep = "\t", quote = FALSE)

OUT_TIC <- file.path(OUT, "list.txt")
write.table(TIC, file = OUT_TIC, row.names = FALSE, col.names = FALSE, quote = FALSE)

PLOT_VOLCANO <- file.path(OUT, "volcano.pdf")
pdf(PLOT_VOLCANO, width = 4.5, height = 5)
M <- max(abs(df_wilcox$log2fc))+1
plot(df_wilcox$log2fc, -log10(df_wilcox$pval), xlab = "log2(FC)", ylab = "-log10(pval)", pch = 16, col = "gray", main = "Tumor-parental", sub = "[Wilcoxon rank-sum test]", xlim = c(-M,M))
abline(h = 1, lty = 2)
abline(v = 0, lty = 2)
points(x = df_wilcox$log2fc[idx_TIC], y = -log10(df_wilcox$pval[idx_TIC]), pch = 16, col = "blue")
legend("topright", legend = c("TIC","non-TIC"), col = c("blue","gray"), pch = 16)
dev.off()

PLOT_MA <- file.path(OUT, "ma.pdf")
pdf(PLOT_MA, width = 4.5, height = 5)
plot(df_wilcox$log.avg, df_wilcox$log2fc, xlab = "mean(log2(CPM))", ylab = "log2(FC)", pch = 16, col = "gray", main = "Tumor-parental", ylim = c(-M,M))
abline(h = 0, lty = 2)
points(x = df_wilcox$log.avg[idx_TIC], y = df_wilcox$log2fc[idx_TIC], pch = 16, col = "blue")
legend("bottomright", legend = c("TIC","non-TIC"), col = c("blue","gray"), pch = 16)
dev.off()

q()


