
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 5) {
    cat("\nUsage: <cpm> <file_list> <control> <case> <outdir>\n")
    cat("\n<cpm>         normalized count for each GBC\n")
    cat("<file_list>   tsv containing the sample ID (col1) and the path of the \"groups.tsv\" (col2) generated by barcode-groups\n")
    cat("<control>     label defining the control (as in <file_list> col3)\n")
    cat("<case>        label defining the case (as in <file_list> col3)\n")
    cat("<outdir>      where the list of TIC and the volcano plot are saved\n\n")
    q()
}

CPM <- args[1]
FILE_LIST <- args[2]
CTRL <- args[3]
CASE <- args[4]
OUT <- args[5]

cpm <- read.table(CPM, header = TRUE, sep = "\t")

file_list <- read.table(FILE_LIST, header = FALSE, sep = "\t")

idx_col_p0 <- match(file_list[file_list[,3] == CTRL,1], colnames(cpm))
idx_col_t <- match(file_list[file_list[,3] == CASE,1], colnames(cpm))

if (length(idx_col_p0) == 1) {
    cpm_p0_avg <- round(cpm[,idx_col_p0])
    names(cpm_p0_avg) <- rownames(cpm)
} else {
    cpm_p0_avg <- apply(cpm[,idx_col_p0], 1, function(x) round(mean(x)))
}

x <- rep(cpm_p0_avg, length(idx_col_t))
y <- c()
for (i in idx_col_t) {
    y <- c(y, cpm[,i])
}
df <- data.frame(x = log2(x), y = log2(y/x), z = names(x))

library("ggplot2")
library("mgcv")

idx <- which(!is.infinite(df$y) & !is.infinite(df$x))
df <- df[idx,]

PLOT_GAM <- file.path(OUT, "dotplot.pdf")
pdf(PLOT_GAM, width = 5, height = 5)
ggplot(df, aes(x = x, y = y)) + geom_point() + geom_smooth()
dev.off()

fit.gam <- gam(df$y ~ s(df$x, bs = "cs"))
df <- cbind(df, fit.gam$residuals > 0)
colnames(df) <- c("log2.cpm", "log2.fc", "gbc.id", "is.selected")
df_gam <- table(df[,3:4])

OCC <- ceiling(length(idx_col_t)/2+1)
idx_TIC <- which(df_gam[,2] >= OCC)
TIC <- rownames(df_gam)[idx_TIC]

is.TIC <- rep(FALSE, nrow(df_gam))
is.TIC[idx_TIC] <- rep(TRUE, length(idx_TIC))
df_gam <- cbind(cpm[match(rownames(df_gam),rownames(cpm)),], occ = df_gam[,2], is.selected = as.numeric(is.TIC))

idx <- match(df$gbc.id, rownames(df_gam))
df <- cbind(df[,1:2], is.selected = df_gam$is.selected[idx])
df$is.selected <- as.factor(as.character(df$is.selected))

PLOT_GAM <- file.path(OUT, "dotplot_colBySel.pdf")
pdf(PLOT_GAM, width = 5.5, height = 5)
ggplot(df, aes(x = log2.cpm, y = log2.fc)) + geom_point(aes(color = is.selected)) + geom_smooth()
dev.off()

OUT_TIC <- file.path(OUT, "gam.tsv")
write.table(df_gam, file = OUT_TIC, sep = "\t", quote = FALSE)

OUT_TIC <- file.path(OUT, "list.txt")
write.table(TIC, file = OUT_TIC, row.names = FALSE, col.names = FALSE, quote = FALSE)

q()



