
# pseudo-count
PSC <- 10

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 5) {
    cat("\nUsage: <file_list> <in.tsv> <out.tsv> <control> <case>\n")
    cat("\n<file_list>   tsv containing the sample ID (col1) and the path of the \"groups.tsv\" (col2) generated by barcode-groups\n")
    cat("<in.tsv>      table containing the library-normalized count (cpm)\n")
    cat("<out.tsv>     table containing the log2FC of each case vs the average of the controls\n")
    cat("<control>     label defining the control (as in <file_list> col3)\n")
    cat("<case>        label defining the case (as in <file_list> col3)\n")
    q()
}

FILE_LIST <- args[1]
IN <- args[2]
OUT <- args[3]
CTRL <- args[4]
CASE <- args[5]

file_list <- read.table(FILE_LIST, header = FALSE, sep = "\t")
cpm <- read.table(IN, header = TRUE, sep = "\t")

# compute cpm average across controls
idx <- match(file_list[file_list[,3] == CTRL,1], colnames(cpm))
if (length(idx) == 1) {
    cpm_P0_avg <- cpm[,idx]
} else {
    cpm_P0_avg <- apply(cpm[,idx], 1, mean)
}

# initialize the log2FC matrix
idx <- match(file_list[file_list[,3] == CASE,1], colnames(cpm))
log2FC <- matrix(NA, nrow = nrow(cpm), ncol = length(idx))
rownames(log2FC) <- rownames(cpm)
colnames(log2FC) <- colnames(cpm)[idx]

# populate the log2FC matrix
for (i in 1:length(idx)) {
    log2FC[,i] <- log2((cpm[,idx[i]]+PSC)/(cpm_P0_avg+PSC))
}

# write to file
write.table(log2FC, file = OUT, sep = "\t", quote = FALSE)

q()


