
# pseudo-count
PSC <- 10

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 5) {
    cat("\nUsage: <file_list> <in.tsv> <out.tsv> <control> <case>\n")
    cat("\n<file_list>   tsv containing the sample ID (col1) and the path of the \"groups.tsv\" (col2) generated by barcode-groups\n")
    cat("<in.tsv>      table containing the library-normalized count (cpm)\n")
    cat("<out.tsv>     table containing the M and A stats case vs controls\n")
    cat("<control>     label defining the control (as in <file_list> col3)\n")
    cat("<case>        label defining the case (as in <file_list> col3)\n")
    q()
}

FILE_LIST <- args[1]
IN <- args[2]
OUT <- args[3]
CTRL <- args[4]
CASE <- args[5]

file_list <- read.table(FILE_LIST, header = FALSE, sep = "\t")
cpm <- read.table(IN, header = TRUE, sep = "\t")

# compute the log cpm average across controls
idx <- match(file_list[file_list[,3] == CTRL,1], colnames(cpm))
if (length(idx) == 1) {
    cpm_ctrl_avg <- cpm[,idx]
} else {
    cpm_ctrl_avg <- apply(cpm[,idx], 1, mean)
}
log_cpm_ctrl <- log2(cpm_ctrl_avg+PSC)

# compute the log cpm average across cases
idx <- match(file_list[file_list[,3] == CASE,1], colnames(cpm))
if (length(idx) == 1) {
    cpm_case_avg <- cpm[,idx]
} else {
    cpm_case_avg <- apply(cpm[,idx], 1, mean)
}
log_cpm_case <- log2(cpm_case_avg+PSC)

# initialize the log2FC matrix
ma <- data.frame(M = log_cpm_case - log_cpm_ctrl, A = (log_cpm_case + log_cpm_ctrl) / 2)
rownames(ma) <- rownames(cpm)

# write to file
write.table(ma, file = OUT, sep = "\t", quote = FALSE)

q()


