
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 5) {
    cat("\nUsage: <file_list> <indir> <case> <size> <out>\n")
    cat("\n<file_list>  tsv containing the sample ID (col1) and the path of the \"groups.tsv\" (col2) generated by barcode-groups\n")
    cat("<indir>      directory containing the \"*_sel.tsv\" files\n")
    cat("<case>       label defining the case (as in <file_list> col3)\n")
    cat("<size>       total size of the population\n")
    cat("<out>        table containing the output of SuperExactTest\n")
    q()
}

FILE_LIST <- args[1]
INDIR <- args[2]
CASE <- args[3]
SIZE <- as.numeric(args[4])
OUT <- args[5]

library("SuperExactTest")

file_list <- read.table(FILE_LIST, sep = "\t")
samples <- file_list[file_list[,3] == CASE,1]

l <- list()
i <- 1 
for (s in samples) {
    gbc <- read.table(paste0(INDIR, "/", s, "_sel.txt"))[,1]
    l[[i]] <- gbc
    i <- i+1
}

res <- supertest(l, n=SIZE)

df <- data.frame(overlap.sizes = res$overlap.sizes, overlap.expected = res$overlap.expected, P.value = res$P.value)
rownames(df) <- names(res$P.value)
write.table(df, file = OUT, sep = "\t", quote = FALSE)

ub <- c(1)
for (i in 2:length(res$x)) {
    num_sets <- unlist(lapply( names(res$P.value), function(x) sum(as.numeric(unlist(strsplit(x,split="")))) ))
    idx <- which(num_sets == i)
    p <- sum(res$P.value[idx])
    ub <- c(ub, p)
}




q()


